### ISSUE TITLE
Feature Suggestion: Pad as a controllable parameter in plot

### ISSUE THREAD

**Issue by michaelmarty** [mobiusklein/pygly2#23]
Great library! One feature suggestion, on the plots, it would be helpful to have a controllable parameter for the padding. I thought the defaults had too much padding around the edge, so I added in a controllable parameter for the pad and pad factor. If you'd be interested in posting it, I'm happy to create a pull request or send you the py file to upload. Thanks,
MTM

**Comment by mobiusklein** [comment]
If you want to open a PR, I'd be happy to review and merge it.

**Comment by michaelmarty** [comment]
Awesome! It's open now. You might need to edit the doc string. I did my best with the units but wasn't 100% sure.

**Comment by mobiusklein** [comment]
Thank you for submitting the PR. It looked right, and I've merged it now. I'll set up a new release on PyPI shortly.
